kind: pipeline
type: docker
name: deploy_production

platform:
  os: linux
  arch: arm64

steps:
  - name: Get git commit tag
    image: alpine
    commands:
      - apk add git
      - git rev-parse --short HEAD > .tag
      - cat .tag
  - name: Upgrade our helm chart with new tag
    image: alpine/k8s:1.23.16
    environment:
      KUBECONFIG_DATA:
        from_secret: KUBECONFIG_DATA
    commands:
      - kubectl get namespaces --kubeconfig <(echo $KUBECONFIG_DATA)

# depends_on:
#   - build_image