{{ range $i, $e := until (int $.Values.replicas) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-{{ $i }}
spec:
  selector:
    matchLabels:
      app: lobby-{{ $i }}
  template:
    metadata:
      labels:
        app: lobby-{{ $i }}
    spec:
      containers:
        - name: lobby
          image: {{ $.Values.image }}:{{ $.Values.tag }}
          env:
            - name: "VELOCITY_FORWARDING_SECRET"
              value: {{ $.Values.forwardingSecret }}
            - name: "RESOURCEPACK_DOWNLOAD_LINK"
              value: https://resourcepack.lobby-{{ $i }}.playbox.k8s.odzi.dog

---
apiVersion: v1
kind: Service
metadata:
  name: lobby-{{ $i }}
spec:
  type: ClusterIP
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: entrypoint
  - port: 25567
    targetPort: 25567
    protocol: TCP
    name: resourcepack
  selector:
    app: lobby-{{ $i }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lobby-{{ i }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`resourcepack.{{ lobby-$i }}.playbox.k8s.odzi.dog`)
      kind: Rule
      services:
        - name: lobby-{{ $i }}
          port: "resourcepack"
  tls:
    certResolver: "cloudflare"
{{ end }}